kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gtoken-webhook-crb 
  labels:
    app: gtoken-webhook
subjects:
- kind: ServiceAccount
  name: gtoken-webhook-sa
  namespace: gtoken
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gtoken-webhook-cr
