apiVersion: v2
name: cloud-sql-proxy-operator
description: A Helm chart for Kubernetes
type: application
version: 1.1.0
appVersion: "1.0.0"

dependencies:
- name: crds
  condition: crds.enabled
  version: 0.0.0
