---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: zombie-pod-killer
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: zombie-pod-killer
data:
{{ (.Files.Glob "scripts/zombie-pod-killer.sh").AsConfig | indent 2 }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: zombie-pod-killer
  {{- with .Values.labels}}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec: # Cron Job
  schedule: {{ .Values.cron | quote }}
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata: # Job
      {{- with .Values.labels}}
      labels:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      backoffLimit: 2
      template:
        metadata: # Pod
          {{- with .Values.labels}}
          labels:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        spec:
          serviceAccountName: zombie-pod-killer
          {{- with .Values.podSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          containers:
          - name: zombie-pod-killer
            {{- with .Values.securityContext }}
            securityContext:
              {{- toYaml . | nindent 14 }}
            {{- end }}
            image: bitnami/kubectl
            command: ["/bin/sh", "-c"]
            args: ["cat /bin/entrypoint.sh && /bin/entrypoint.sh"]
            volumeMounts:
            - name: configmap-volume
              mountPath: /bin/entrypoint.sh
              readOnly: true
              subPath: zombie-pod-killer.sh
          volumes:
          - name: configmap-volume
            configMap:
              defaultMode: 0770
              name: zombie-pod-killer
          restartPolicy: Never
