apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: zombie-pod-killer
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "delete", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: zombie-pod-killer
subjects:
- kind: ServiceAccount
  name: zombie-pod-killer
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: zombie-pod-killer
  apiGroup: "rbac.authorization.k8s.io"
