---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/cloud-sql-proxy-operator-serving-cert
  name: cloud-sql-proxy-operator-mutating-core-webhook-configuration
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: cloud-sql-proxy-operator-webhook-service
        namespace: {{ .Release.Namespace }}
        path: /mutate-pods
    failurePolicy: Ignore
    matchPolicy: Equivalent
    name: pods.proxy.cloudsql.google.com
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - pods
        scope: '*'
    sideEffects: None
    timeoutSeconds: 2
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/cloud-sql-proxy-operator-serving-cert
  name: cloud-sql-proxy-operator-mutating-webhook-configuration
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: cloud-sql-proxy-operator-webhook-service
        namespace: {{ .Release.Namespace }}
        path: /mutate-cloudsql-cloud-google-com-v1-authproxyworkload
    failurePolicy: Fail
    name: mauthproxyworkload.kb.io
    rules:
      - apiGroups:
          - cloudsql.cloud.google.com
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - authproxyworkloads
    sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/cloud-sql-proxy-operator-serving-cert
  name: cloud-sql-proxy-operator-validating-webhook-configuration
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: cloud-sql-proxy-operator-webhook-service
        namespace: {{ .Release.Namespace }}
        path: /validate-cloudsql-cloud-google-com-v1-authproxyworkload
    failurePolicy: Fail
    name: vauthproxyworkload.kb.io
    rules:
      - apiGroups:
          - cloudsql.cloud.google.com
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - authproxyworkloads
    sideEffects: None
