---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cloud-sql-proxy-operator-serving-cert
  namespace: {{ .Release.Namespace }}
spec:
  dnsNames:
    - cloud-sql-proxy-operator-webhook-service.{{ .Release.Namespace }}.svc
    - cloud-sql-proxy-operator-webhook-service.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: cloud-sql-proxy-operator-selfsigned-issuer
  secretName: webhook-server-cert
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: cloud-sql-proxy-operator-selfsigned-issuer
  namespace: {{ .Release.Namespace }}
spec:
  selfSigned: {}
